package com.hzbhd.canbus.adapter.util;

import android.content.Context;

public class CanTypeMsg {
   public static final String BHD = "BHD";
   public static final String BINARY = "BINARY";
   public static final String CYT = "CYT";
   public static final String DOGEN = "DOGEN";
   public static final String HIWORLD = "HIWORLD";
   public static final String LUZHENG = "LUZHENG";
   public static final String OTHER = "OTHER";
   public static final String OUDI = "OUDI";
   public static final String RAISE = "RAISE";
   public static final String SIMPLE = "SIMPLE";
   public static final String XFY = "XFY";
   public static final String XINBAS = "XINBAS";

   public static enum CAN_TYPE_ID {
      private static final CAN_TYPE_ID[] $VALUES;
      ACCORD_8_OUDI,
      AT360_OTHER,
      AUDI_A3_SIMPLE,
      AUDI_Q3_RAISE,
      BAIC_SHENBAO_RAISE,
      BAIC_WEIWANG_M20_RAISE,
      BAOJ_RAISE,
      BEIJING_BJ40_OUDI,
      BENZ_B200_2015_VITO_HIWORLD,
      BENZ_B200_HIWORLD,
      BENZ_B200_LUZHENG,
      BENZ_B200_SIMPLE,
      BENZ_NO_USE9,
      BENZ_RAISE,
      BENZ_SMART_SIMPLE,
      BENZ_VITO_2015_SIMPLE,
      BESTUNE_X80_2017_RAISE,
      BISU_M3_T3_RAISE,
      BMW5_2E_RAISE,
      BMW_E90_E84_F35_F20_HIWORLD,
      BMW_E90_SIMPLE,
      BUICK_ENCLAVE_HIWORLD,
      BUICK_EXCELLE_2015_SIMPLE,
      BUICK_GL8_2017_RAISE,
      BUICK_GL8_2017_XINBAS,
      BUICK_LACROSSE_SIMPLE,
      CHANGAN_BINARY,
      CHERY_HIWORLD,
      CHERY_RAISE,
      CMC_H3_V3_HIWORLD,
      DONGFENG_FENGGUANG_50_RAISE,
      DONGFENG_FENGGUANG_580_18_RAISE,
      DONGFENG_FENGSHEN_RAISE,
      DONGFENG_JINGYI_X5_RAISE,
      DONGNAN_V5_RAISE,
      ENCLAVE_2013_SIMPLE,
      ENCORE_LOW_RAISE,
      ENCORE_LOW_SIMPLE,
      EXCELLE_VERANO_2015_HIWORLD,
      FABBRICA_RAISE,
      FENGGUANG_RAISE,
      FIAT_AEGEA_DOGE_RAM_1500_SIMPLE,
      FIAT_DOBLO_SIMPLE,
      FIAT_DOBLO_VIAGGIO_HIWORLD,
      FIAT_LINEA_HIWORLD,
      FIAT_VIAGGIO_SIMPLE,
      FORD_ECOSPORT_SIMPLE,
      FORD_ECOSPORT_XINBAS,
      FORD_EDGE_2011_2014_EXPOLER_HIWORLD,
      FORD_EDGE_2013_SIMPLE,
      FORD_EDGE_2013_XINBAS,
      FORD_EDGE_2018_HIWORLD,
      FORD_EDGE_SIMPLE,
      FORD_EDGE_XINBAS,
      FORD_ESCAPE_KUGA_2017_RAISE,
      FORD_ESCAPE_KUGA_SIMPLE,
      FORD_ESCAPE_KUGA_XINBAS,
      FORD_FIESTA_OLD_HIWORLD,
      FORD_FIESTA_SIMPLE,
      FORD_FIESTA_XINBAS,
      FORD_HIWORLD,
      FORD_MONDEO_2011_SIMPLE,
      FORD_MONDEO_2013_HIWORLD,
      FORD_MONDEO_2013_REMOVE_AC_HIWORLD,
      FORD_MONDEO_2017_XINBAS,
      FORD_NO_USE10,
      FORD_NO_USE8,
      FORD_NO_USE9,
      FORD_SIMPLE,
      FORD_SMAX_HIWORLD,
      FORD_XINBAS,
      GEELY_GC7_HIWORLD,
      GEELY_GL_GS_HIWORLD,
      GEELY_RAISE,
      GEELY_VISION_HIWORLD,
      GETU_ELECTRIC_OTHER,
      GL6_HIWORLD,
      GL8_2017_HIWORLD,
      GM_HIWORLD,
      GM_MOST_MODUAL_SIMPLE,
      GM_NO_USE13,
      GM_NO_USE14,
      GM_NO_USE15,
      GM_NO_USE16,
      GM_NO_USE17,
      GM_NO_USE18,
      GM_NO_USE19,
      GM_NO_USE20,
      GM_RAISE,
      GM_SIMPLE,
      GM_XINBAS,
      HAIMA_M8_RAISE,
      HAIMA_RAISE,
      HAIMA_S7_S5_FAMILY_RAISE,
      HANTENG_RAISE,
      HANTENG_X7_RAISE,
      HAVAL_H2_HIWORLD,
      HAVAL_H3_SIMPLE,
      HAVAL_H6_COUPE_HIWORLD,
      HAVAL_H6_HIWORLD,
      HONDA_ACCORD_2_0_MIDDLE_LOW_SIMPLE,
      HONDA_ACCORD_2_0_XINBAS,
      HONDA_ACCORD_2_4_CH_MIDDLE_LOW_SIMPLE,
      HONDA_ACCORD_2_4_US_LOW_SIMPLE,
      HONDA_ACCORD_2_4_XINBAS,
      HONDA_ACCORD_7_CYT,
      HONDA_ACCORD_7_DOGEN,
      HONDA_ACCORD_7_WITH_AC_CTRL_CYT,
      HONDA_ACCORD_8_HIWORLD,
      HONDA_ACCORD_8_XINBAS,
      HONDA_ACCORD_BINARY,
      HONDA_ACCORD_LOW_HIWORLD,
      HONDA_CIVIC_2016_SIMPLE,
      HONDA_CIVIC_2016_XINBAS,
      HONDA_CROSSTOUR_RAISE,
      HONDA_CRV_2012_HIWORLD,
      HONDA_CRV_2012_XINBAS,
      HONDA_CRV_2015_HIWORLD,
      HONDA_CRV_2015_XINBAS,
      HONDA_CRV_2017_HIWORLD,
      HONDA_CRV_CIVIC_2012_SIMPLE,
      HONDA_CRV_HIGH_RAISE,
      HONDA_CRV_LOW_RAISE,
      HONDA_DA_SIMPLE,
      HONDA_DA_XINBAS,
      HONDA_HIWORLD,
      HONDA_NO_USE3,
      HONDA_NO_USE4,
      HONDA_RAISE,
      HYUNDAI_KIA_RAISE,
      HYUNDAI_KIA_SIMPLE,
      HYUNDAI_KIA_XINBAS,
      HYUNDAI_SONATA_9_2018_10_PANEL_SIMPLE,
      HYUNDAI_SONATA_9_2018_6_PANEL_SIMPLE,
      HYUNDAI_SONATA_9_2018_8_PANEL_SIMPLE,
      HYUNDAI_SONATA_HIGH_SIMPLE,
      HYUNDAI_SONATA_MIDDLE_SIMPLE,
      JEEP_2017_GRAND_CHEROKEE_RAISE,
      JEEP_2018_COMMANDER_RAISE,
      JEEP_2018_WRANGLER_RAISE,
      JEEP_CHEROKEE_2016_RAISE,
      JEEP_CHEROKEE_2016_SIMPLE,
      JEEP_CHEROKEE_2016_XINBAS,
      JEEP_CHEROKE_RENEGADE_HIWORLD,
      JEEP_CHRYSLER_OLD_SIMPLE,
      JEEP_COMPASS_2017_HIWORLD,
      JEEP_COMPASS_2017_RAISE,
      JEEP_COMPASS_2017_SIMPLE,
      JEEP_COMPASS_2017_XINBAS,
      JEEP_OLD_COMPASS_WRANGLER_HIWORLD,
      JEEP_OTHER,
      JEEP_RENEGADE_2016_RAISE,
      JEEP_RENEGADE_2016_SIMPLE,
      JEEP_RENEGADE_2016_XINBAS,
      KIA_HYUNDAI_HIWORLD,
      KIA_K5_HIGH_RUSSIA_SIMPLE,
      KIA_K5_HIGH_SIMPLE,
      KIA_K5_MIDDLE_SIMPLE,
      KIA_KX5_HIGH_SIMPLE,
      KIA_KX5_MIDDLE_SIMPLE,
      KIA_SORENTO_SIMPLE,
      KIA_SORENTO_XINBAS,
      KOLEO_2017_RAISE,
      LEXUS_QIZHI_SIMPLE,
      MALIBU_2016_HIWORLD,
      MALIBU_LOW_SIMPLE,
      MAZDA6_2010_HIWORLD,
      MAZDA_3_MAZDA_6_2017_XINBAS,
      MAZDA_6_2010_XINBAS,
      MAZDA_6_2017_SIMPLE,
      MAZDA_6_CX5_2013_SIMPLE,
      MAZDA_6_LUZHENG,
      MAZDA_6_XINBAS,
      MAZDA_AXELA_HIWORLD,
      MAZDA_BINARY,
      MAZDA_BT_50_SIMPLE,
      MAZDA_HIWORLD,
      MAZDA_OLD_RAISE,
      MAZDA_RAISE,
      MAZDA_SIMPLE,
      MG_RAISE,
      MISTRA_HIWORLD,
      MITSUBISHI_OUTLANDER_2014_SIMPLE,
      NEW_PEUGEOT_206_SIMPLE,
      NEW_SAMAND_XS_SIMPLE,
      NEW_TOYOTA_HIWORLD,
      NISSAN_HIWORLD,
      NISSAN_JUN_JUKE_RAISE,
      NISSAN_KRORAINA_SIMA_RAISE,
      NISSAN_MURANO_SIMPLE,
      NISSAN_NO_USE4,
      NISSAN_NO_USE5,
      NISSAN_SIMPLE,
      NISSAN_TEANA_08_SIMPLE,
      NISSAN_TEANA_RAISE,
      NISSAN_X_TRAIL_HIGHT_SIMPLE,
      NO_CAN,
      OLD_AUDI_A3_HIWORLD,
      OPEL_ASTRA_SIMPLE,
      PEUGEOT_206_SIMPLE,
      PEUGEOT_307_408_3008_RAISE,
      PEUGEOT_NO_USE02,
      PEUGEOT_NO_USE03,
      PEUGEOT_NO_USE04,
      PEUGEOT_NO_USE05,
      PEUGEOT_NO_USE06,
      PEUGEOT_NO_USE10,
      PEUGEOT_NO_USE4,
      PEUGEOT_NO_USE5,
      PEUGEOT_NO_USE6,
      PEUGEOT_NO_USE7,
      PEUGEOT_NO_USE8,
      PEUGEOT_NO_USE9,
      PORSCHE_2009_CAYENNE_SIMPLE,
      PROJECT_212_XINBAS,
      PROJECT_3163_KZ,
      PSA_AC_CONTRL_RAISE,
      PSA_HIWORLD,
      PSA_NO_USE04,
      PSA_NO_USE05,
      PSA_NO_USE06,
      PSA_NO_USE07,
      PSA_NO_USE08,
      PSA_NO_USE09,
      PSA_NO_USE10,
      PSA_RAISE,
      PSA_SIMPLE,
      PSA_TOUCH_AIR_SIMPLE,
      RENAULT_HIWORLD,
      RENAULT_KOLEOS2_AIR_AUTO_SIMPLE,
      RENAULT_KOLEOS2_AIR_MANUAL_SIMPLE,
      RENAULT_MEGANE_3_SIMPLE,
      RENAUL_DACIA_SIMPLE,
      RENUALT_RAISE,
      ROEWE_RAISE,
      SAIL_3_HIWORLD,
      SENOVA_D60_BEIJING_BJ20_OUDI,
      SENOVA_X25_X55_OUDI,
      SENOVA_X35_CHANGHE_Q35_OUDI,
      SHANGQI_DATONG_RAISE,
      SUBARU_XINBAS,
      THRUMPCHI_RAISE,
      TOYOTA_BINARY,
      TOYOTA_HIWORLD,
      TOYOTA_NO_USE8,
      TOYOTA_NO_USE9,
      TOYOTA_PRADO_2014_RAISE,
      TOYOTA_PRADO_2014_SIMPLE,
      TOYOTA_PRADO_2014_XINBAS,
      TOYOTA_RAISE,
      TOYOTA_SIMPLE,
      TOYOTA_VERTICAL_XFY,
      TOYOTA_XINBAS,
      TRUMPCHI_HIWORLD,
      TUCSON_2016_HIWORLD,
      VOLVO_XFY,
      VW_MQB_HIWORLD,
      VW_MQB_RAISE,
      VW_MQB_SIMPLE,
      VW_NO_USE4,
      VW_NO_USE5,
      VW_NO_USE6,
      VW_NO_USE7,
      VW_NO_USE8,
      VW_SKODA_HIWORLD,
      VW_SKODA_RAISE,
      VW_SKODA_SIMPLE,
      WEIWANG_M50F_OUDI,
      YQ_NEW_ENERY_OTHER;

      static {
         CAN_TYPE_ID var264 = new CAN_TYPE_ID("NO_CAN", 0);
         NO_CAN = var264;
         CAN_TYPE_ID var211 = new CAN_TYPE_ID("VW_SKODA_SIMPLE", 1);
         VW_SKODA_SIMPLE = var211;
         CAN_TYPE_ID var54 = new CAN_TYPE_ID("VW_MQB_SIMPLE", 2);
         VW_MQB_SIMPLE = var54;
         CAN_TYPE_ID var103 = new CAN_TYPE_ID("VW_MQB_RAISE", 3);
         VW_MQB_RAISE = var103;
         CAN_TYPE_ID var171 = new CAN_TYPE_ID("VW_SKODA_RAISE", 4);
         VW_SKODA_RAISE = var171;
         CAN_TYPE_ID var127 = new CAN_TYPE_ID("VW_SKODA_HIWORLD", 5);
         VW_SKODA_HIWORLD = var127;
         CAN_TYPE_ID var27 = new CAN_TYPE_ID("VW_NO_USE4", 6);
         VW_NO_USE4 = var27;
         CAN_TYPE_ID var190 = new CAN_TYPE_ID("VW_NO_USE5", 7);
         VW_NO_USE5 = var190;
         CAN_TYPE_ID var228 = new CAN_TYPE_ID("VW_NO_USE6", 8);
         VW_NO_USE6 = var228;
         CAN_TYPE_ID var242 = new CAN_TYPE_ID("VW_NO_USE7", 9);
         VW_NO_USE7 = var242;
         CAN_TYPE_ID var241 = new CAN_TYPE_ID("VW_NO_USE8", 10);
         VW_NO_USE8 = var241;
         CAN_TYPE_ID var166 = new CAN_TYPE_ID("TOYOTA_SIMPLE", 11);
         TOYOTA_SIMPLE = var166;
         CAN_TYPE_ID var136 = new CAN_TYPE_ID("TOYOTA_HIWORLD", 12);
         TOYOTA_HIWORLD = var136;
         CAN_TYPE_ID var157 = new CAN_TYPE_ID("TOYOTA_PRADO_2014_SIMPLE", 13);
         TOYOTA_PRADO_2014_SIMPLE = var157;
         CAN_TYPE_ID var131 = new CAN_TYPE_ID("TOYOTA_XINBAS", 14);
         TOYOTA_XINBAS = var131;
         CAN_TYPE_ID var31 = new CAN_TYPE_ID("TOYOTA_PRADO_2014_XINBAS", 15);
         TOYOTA_PRADO_2014_XINBAS = var31;
         CAN_TYPE_ID var24 = new CAN_TYPE_ID("TOYOTA_RAISE", 16);
         TOYOTA_RAISE = var24;
         CAN_TYPE_ID var123 = new CAN_TYPE_ID("TOYOTA_PRADO_2014_RAISE", 17);
         TOYOTA_PRADO_2014_RAISE = var123;
         CAN_TYPE_ID var25 = new CAN_TYPE_ID("NEW_TOYOTA_HIWORLD", 18);
         NEW_TOYOTA_HIWORLD = var25;
         CAN_TYPE_ID var206 = new CAN_TYPE_ID("TOYOTA_NO_USE8", 19);
         TOYOTA_NO_USE8 = var206;
         CAN_TYPE_ID var132 = new CAN_TYPE_ID("TOYOTA_NO_USE9", 20);
         TOYOTA_NO_USE9 = var132;
         CAN_TYPE_ID var7 = new CAN_TYPE_ID("NISSAN_SIMPLE", 21);
         NISSAN_SIMPLE = var7;
         CAN_TYPE_ID var93 = new CAN_TYPE_ID("NISSAN_MURANO_SIMPLE", 22);
         NISSAN_MURANO_SIMPLE = var93;
         CAN_TYPE_ID var138 = new CAN_TYPE_ID("NISSAN_HIWORLD", 23);
         NISSAN_HIWORLD = var138;
         CAN_TYPE_ID var21 = new CAN_TYPE_ID("NISSAN_TEANA_08_SIMPLE", 24);
         NISSAN_TEANA_08_SIMPLE = var21;
         CAN_TYPE_ID var198 = new CAN_TYPE_ID("NISSAN_X_TRAIL_HIGHT_SIMPLE", 25);
         NISSAN_X_TRAIL_HIGHT_SIMPLE = var198;
         CAN_TYPE_ID var75 = new CAN_TYPE_ID("NISSAN_NO_USE4", 26);
         NISSAN_NO_USE4 = var75;
         CAN_TYPE_ID var133 = new CAN_TYPE_ID("NISSAN_NO_USE5", 27);
         NISSAN_NO_USE5 = var133;
         CAN_TYPE_ID var128 = new CAN_TYPE_ID("MISTRA_HIWORLD", 28);
         MISTRA_HIWORLD = var128;
         CAN_TYPE_ID var87 = new CAN_TYPE_ID("KIA_HYUNDAI_HIWORLD", 29);
         KIA_HYUNDAI_HIWORLD = var87;
         CAN_TYPE_ID var222 = new CAN_TYPE_ID("HYUNDAI_KIA_RAISE", 30);
         HYUNDAI_KIA_RAISE = var222;
         CAN_TYPE_ID var28 = new CAN_TYPE_ID("HYUNDAI_KIA_SIMPLE", 31);
         HYUNDAI_KIA_SIMPLE = var28;
         CAN_TYPE_ID var88 = new CAN_TYPE_ID("KIA_K5_MIDDLE_SIMPLE", 32);
         KIA_K5_MIDDLE_SIMPLE = var88;
         CAN_TYPE_ID var143 = new CAN_TYPE_ID("KIA_K5_HIGH_SIMPLE", 33);
         KIA_K5_HIGH_SIMPLE = var143;
         CAN_TYPE_ID var79 = new CAN_TYPE_ID("KIA_KX5_MIDDLE_SIMPLE", 34);
         KIA_KX5_MIDDLE_SIMPLE = var79;
         CAN_TYPE_ID var4 = new CAN_TYPE_ID("KIA_KX5_HIGH_SIMPLE", 35);
         KIA_KX5_HIGH_SIMPLE = var4;
         CAN_TYPE_ID var35 = new CAN_TYPE_ID("HYUNDAI_SONATA_MIDDLE_SIMPLE", 36);
         HYUNDAI_SONATA_MIDDLE_SIMPLE = var35;
         CAN_TYPE_ID var52 = new CAN_TYPE_ID("HYUNDAI_SONATA_HIGH_SIMPLE", 37);
         HYUNDAI_SONATA_HIGH_SIMPLE = var52;
         CAN_TYPE_ID var8 = new CAN_TYPE_ID("KIA_SORENTO_SIMPLE", 38);
         KIA_SORENTO_SIMPLE = var8;
         CAN_TYPE_ID var169 = new CAN_TYPE_ID("HYUNDAI_KIA_XINBAS", 39);
         HYUNDAI_KIA_XINBAS = var169;
         CAN_TYPE_ID var85 = new CAN_TYPE_ID("KIA_SORENTO_XINBAS", 40);
         KIA_SORENTO_XINBAS = var85;
         CAN_TYPE_ID var37 = new CAN_TYPE_ID("HONDA_DA_SIMPLE", 41);
         HONDA_DA_SIMPLE = var37;
         CAN_TYPE_ID var256 = new CAN_TYPE_ID("HONDA_CRV_CIVIC_2012_SIMPLE", 42);
         HONDA_CRV_CIVIC_2012_SIMPLE = var256;
         CAN_TYPE_ID var81 = new CAN_TYPE_ID("HONDA_DA_XINBAS", 43);
         HONDA_DA_XINBAS = var81;
         CAN_TYPE_ID var216 = new CAN_TYPE_ID("HONDA_CRV_2015_XINBAS", 44);
         HONDA_CRV_2015_XINBAS = var216;
         CAN_TYPE_ID var266 = new CAN_TYPE_ID("HONDA_CRV_2012_XINBAS", 45);
         HONDA_CRV_2012_XINBAS = var266;
         CAN_TYPE_ID var146 = new CAN_TYPE_ID("HONDA_CIVIC_2016_SIMPLE", 46);
         HONDA_CIVIC_2016_SIMPLE = var146;
         CAN_TYPE_ID var114 = new CAN_TYPE_ID("HONDA_CIVIC_2016_XINBAS", 47);
         HONDA_CIVIC_2016_XINBAS = var114;
         CAN_TYPE_ID var267 = new CAN_TYPE_ID("HONDA_ACCORD_2_0_MIDDLE_LOW_SIMPLE", 48);
         HONDA_ACCORD_2_0_MIDDLE_LOW_SIMPLE = var267;
         CAN_TYPE_ID var212 = new CAN_TYPE_ID("HONDA_ACCORD_2_4_CH_MIDDLE_LOW_SIMPLE", 49);
         HONDA_ACCORD_2_4_CH_MIDDLE_LOW_SIMPLE = var212;
         CAN_TYPE_ID var257 = new CAN_TYPE_ID("HONDA_ACCORD_2_4_US_LOW_SIMPLE", 50);
         HONDA_ACCORD_2_4_US_LOW_SIMPLE = var257;
         CAN_TYPE_ID var150 = new CAN_TYPE_ID("HONDA_ACCORD_2_0_XINBAS", 51);
         HONDA_ACCORD_2_0_XINBAS = var150;
         CAN_TYPE_ID var167 = new CAN_TYPE_ID("HONDA_ACCORD_2_4_XINBAS", 52);
         HONDA_ACCORD_2_4_XINBAS = var167;
         CAN_TYPE_ID var265 = new CAN_TYPE_ID("HONDA_NO_USE3", 53);
         HONDA_NO_USE3 = var265;
         CAN_TYPE_ID var69 = new CAN_TYPE_ID("HONDA_NO_USE4", 54);
         HONDA_NO_USE4 = var69;
         CAN_TYPE_ID var9 = new CAN_TYPE_ID("HONDA_HIWORLD", 55);
         HONDA_HIWORLD = var9;
         CAN_TYPE_ID var12 = new CAN_TYPE_ID("HONDA_CRV_2017_HIWORLD", 56);
         HONDA_CRV_2017_HIWORLD = var12;
         CAN_TYPE_ID var188 = new CAN_TYPE_ID("HONDA_CRV_2015_HIWORLD", 57);
         HONDA_CRV_2015_HIWORLD = var188;
         CAN_TYPE_ID var184 = new CAN_TYPE_ID("HONDA_CRV_2012_HIWORLD", 58);
         HONDA_CRV_2012_HIWORLD = var184;
         CAN_TYPE_ID var130 = new CAN_TYPE_ID("HONDA_ACCORD_LOW_HIWORLD", 59);
         HONDA_ACCORD_LOW_HIWORLD = var130;
         CAN_TYPE_ID var160 = new CAN_TYPE_ID("MAZDA_SIMPLE", 60);
         MAZDA_SIMPLE = var160;
         CAN_TYPE_ID var140 = new CAN_TYPE_ID("GM_SIMPLE", 61);
         GM_SIMPLE = var140;
         CAN_TYPE_ID var240 = new CAN_TYPE_ID("GM_XINBAS", 62);
         GM_XINBAS = var240;
         CAN_TYPE_ID var263 = new CAN_TYPE_ID("ENCORE_LOW_SIMPLE", 63);
         ENCORE_LOW_SIMPLE = var263;
         CAN_TYPE_ID var121 = new CAN_TYPE_ID("MALIBU_LOW_SIMPLE", 64);
         MALIBU_LOW_SIMPLE = var121;
         CAN_TYPE_ID var246 = new CAN_TYPE_ID("OPEL_ASTRA_SIMPLE", 65);
         OPEL_ASTRA_SIMPLE = var246;
         CAN_TYPE_ID var100 = new CAN_TYPE_ID("BUICK_EXCELLE_2015_SIMPLE", 66);
         BUICK_EXCELLE_2015_SIMPLE = var100;
         CAN_TYPE_ID var151 = new CAN_TYPE_ID("BUICK_LACROSSE_SIMPLE", 67);
         BUICK_LACROSSE_SIMPLE = var151;
         CAN_TYPE_ID var187 = new CAN_TYPE_ID("GM_RAISE", 68);
         GM_RAISE = var187;
         CAN_TYPE_ID var117 = new CAN_TYPE_ID("ENCORE_LOW_RAISE", 69);
         ENCORE_LOW_RAISE = var117;
         CAN_TYPE_ID var214 = new CAN_TYPE_ID("BUICK_GL8_2017_RAISE", 70);
         BUICK_GL8_2017_RAISE = var214;
         CAN_TYPE_ID var104 = new CAN_TYPE_ID("BUICK_GL8_2017_XINBAS", 71);
         BUICK_GL8_2017_XINBAS = var104;
         CAN_TYPE_ID var19 = new CAN_TYPE_ID("ENCLAVE_2013_SIMPLE", 72);
         ENCLAVE_2013_SIMPLE = var19;
         CAN_TYPE_ID var173 = new CAN_TYPE_ID("GM_NO_USE13", 73);
         GM_NO_USE13 = var173;
         CAN_TYPE_ID var260 = new CAN_TYPE_ID("GM_NO_USE14", 74);
         GM_NO_USE14 = var260;
         CAN_TYPE_ID var249 = new CAN_TYPE_ID("GM_NO_USE15", 75);
         GM_NO_USE15 = var249;
         CAN_TYPE_ID var73 = new CAN_TYPE_ID("GM_NO_USE16", 76);
         GM_NO_USE16 = var73;
         CAN_TYPE_ID var233 = new CAN_TYPE_ID("GM_NO_USE17", 77);
         GM_NO_USE17 = var233;
         CAN_TYPE_ID var250 = new CAN_TYPE_ID("GM_NO_USE18", 78);
         GM_NO_USE18 = var250;
         CAN_TYPE_ID var10 = new CAN_TYPE_ID("GM_NO_USE19", 79);
         GM_NO_USE19 = var10;
         CAN_TYPE_ID var44 = new CAN_TYPE_ID("GM_NO_USE20", 80);
         GM_NO_USE20 = var44;
         CAN_TYPE_ID var213 = new CAN_TYPE_ID("FORD_SIMPLE", 81);
         FORD_SIMPLE = var213;
         CAN_TYPE_ID var175 = new CAN_TYPE_ID("FORD_ESCAPE_KUGA_SIMPLE", 82);
         FORD_ESCAPE_KUGA_SIMPLE = var175;
         CAN_TYPE_ID var55 = new CAN_TYPE_ID("FORD_ECOSPORT_SIMPLE", 83);
         FORD_ECOSPORT_SIMPLE = var55;
         CAN_TYPE_ID var159 = new CAN_TYPE_ID("FORD_FIESTA_SIMPLE", 84);
         FORD_FIESTA_SIMPLE = var159;
         CAN_TYPE_ID var26 = new CAN_TYPE_ID("FORD_EDGE_SIMPLE", 85);
         FORD_EDGE_SIMPLE = var26;
         CAN_TYPE_ID var16 = new CAN_TYPE_ID("FORD_MONDEO_2011_SIMPLE", 86);
         FORD_MONDEO_2011_SIMPLE = var16;
         CAN_TYPE_ID var67 = new CAN_TYPE_ID("FORD_XINBAS", 87);
         FORD_XINBAS = var67;
         CAN_TYPE_ID var245 = new CAN_TYPE_ID("FORD_ESCAPE_KUGA_XINBAS", 88);
         FORD_ESCAPE_KUGA_XINBAS = var245;
         CAN_TYPE_ID var65 = new CAN_TYPE_ID("FORD_ECOSPORT_XINBAS", 89);
         FORD_ECOSPORT_XINBAS = var65;
         CAN_TYPE_ID var243 = new CAN_TYPE_ID("FORD_FIESTA_XINBAS", 90);
         FORD_FIESTA_XINBAS = var243;
         CAN_TYPE_ID var2 = new CAN_TYPE_ID("FORD_EDGE_XINBAS", 91);
         FORD_EDGE_XINBAS = var2;
         CAN_TYPE_ID var129 = new CAN_TYPE_ID("FORD_EDGE_2013_XINBAS", 92);
         FORD_EDGE_2013_XINBAS = var129;
         CAN_TYPE_ID var18 = new CAN_TYPE_ID("FORD_MONDEO_2017_XINBAS", 93);
         FORD_MONDEO_2017_XINBAS = var18;
         CAN_TYPE_ID var191 = new CAN_TYPE_ID("FORD_ESCAPE_KUGA_2017_RAISE", 94);
         FORD_ESCAPE_KUGA_2017_RAISE = var191;
         CAN_TYPE_ID var118 = new CAN_TYPE_ID("FORD_EDGE_2013_SIMPLE", 95);
         FORD_EDGE_2013_SIMPLE = var118;
         CAN_TYPE_ID var153 = new CAN_TYPE_ID("FORD_HIWORLD", 96);
         FORD_HIWORLD = var153;
         CAN_TYPE_ID var89 = new CAN_TYPE_ID("FORD_MONDEO_2013_HIWORLD", 97);
         FORD_MONDEO_2013_HIWORLD = var89;
         CAN_TYPE_ID var189 = new CAN_TYPE_ID("FORD_NO_USE8", 98);
         FORD_NO_USE8 = var189;
         CAN_TYPE_ID var227 = new CAN_TYPE_ID("FORD_NO_USE9", 99);
         FORD_NO_USE9 = var227;
         CAN_TYPE_ID var154 = new CAN_TYPE_ID("FORD_NO_USE10", 100);
         FORD_NO_USE10 = var154;
         CAN_TYPE_ID var106 = new CAN_TYPE_ID("BENZ_B200_SIMPLE", 101);
         BENZ_B200_SIMPLE = var106;
         CAN_TYPE_ID var253 = new CAN_TYPE_ID("BENZ_VITO_2015_SIMPLE", 102);
         BENZ_VITO_2015_SIMPLE = var253;
         CAN_TYPE_ID var236 = new CAN_TYPE_ID("MITSUBISHI_OUTLANDER_2014_SIMPLE", 103);
         MITSUBISHI_OUTLANDER_2014_SIMPLE = var236;
         CAN_TYPE_ID var170 = new CAN_TYPE_ID("BMW_E90_SIMPLE", 104);
         BMW_E90_SIMPLE = var170;
         CAN_TYPE_ID var34 = new CAN_TYPE_ID("AUDI_A3_SIMPLE", 105);
         AUDI_A3_SIMPLE = var34;
         CAN_TYPE_ID var202 = new CAN_TYPE_ID("SUBARU_XINBAS", 106);
         SUBARU_XINBAS = var202;
         CAN_TYPE_ID var223 = new CAN_TYPE_ID("RENAUL_DACIA_SIMPLE", 107);
         RENAUL_DACIA_SIMPLE = var223;
         CAN_TYPE_ID var185 = new CAN_TYPE_ID("PROJECT_212_XINBAS", 108);
         PROJECT_212_XINBAS = var185;
         CAN_TYPE_ID var196 = new CAN_TYPE_ID("BENZ_NO_USE9", 109);
         BENZ_NO_USE9 = var196;
         CAN_TYPE_ID var17 = new CAN_TYPE_ID("FIAT_AEGEA_DOGE_RAM_1500_SIMPLE", 110);
         FIAT_AEGEA_DOGE_RAM_1500_SIMPLE = var17;
         CAN_TYPE_ID var94 = new CAN_TYPE_ID("JEEP_CHRYSLER_OLD_SIMPLE", 111);
         JEEP_CHRYSLER_OLD_SIMPLE = var94;
         CAN_TYPE_ID var125 = new CAN_TYPE_ID("JEEP_CHEROKEE_2016_SIMPLE", 112);
         JEEP_CHEROKEE_2016_SIMPLE = var125;
         CAN_TYPE_ID var229 = new CAN_TYPE_ID("JEEP_RENEGADE_2016_SIMPLE", 113);
         JEEP_RENEGADE_2016_SIMPLE = var229;
         CAN_TYPE_ID var200 = new CAN_TYPE_ID("JEEP_COMPASS_2017_SIMPLE", 114);
         JEEP_COMPASS_2017_SIMPLE = var200;
         CAN_TYPE_ID var61 = new CAN_TYPE_ID("JEEP_CHEROKEE_2016_XINBAS", 115);
         JEEP_CHEROKEE_2016_XINBAS = var61;
         CAN_TYPE_ID var49 = new CAN_TYPE_ID("JEEP_RENEGADE_2016_XINBAS", 116);
         JEEP_RENEGADE_2016_XINBAS = var49;
         CAN_TYPE_ID var172 = new CAN_TYPE_ID("JEEP_COMPASS_2017_XINBAS", 117);
         JEEP_COMPASS_2017_XINBAS = var172;
         CAN_TYPE_ID var220 = new CAN_TYPE_ID("JEEP_CHEROKEE_2016_RAISE", 118);
         JEEP_CHEROKEE_2016_RAISE = var220;
         CAN_TYPE_ID var78 = new CAN_TYPE_ID("JEEP_RENEGADE_2016_RAISE", 119);
         JEEP_RENEGADE_2016_RAISE = var78;
         CAN_TYPE_ID var50 = new CAN_TYPE_ID("JEEP_COMPASS_2017_RAISE", 120);
         JEEP_COMPASS_2017_RAISE = var50;
         CAN_TYPE_ID var255 = new CAN_TYPE_ID("TUCSON_2016_HIWORLD", 121);
         TUCSON_2016_HIWORLD = var255;
         CAN_TYPE_ID var155 = new CAN_TYPE_ID("JEEP_OLD_COMPASS_WRANGLER_HIWORLD", 122);
         JEEP_OLD_COMPASS_WRANGLER_HIWORLD = var155;
         CAN_TYPE_ID var29 = new CAN_TYPE_ID("JEEP_CHEROKE_RENEGADE_HIWORLD", 123);
         JEEP_CHEROKE_RENEGADE_HIWORLD = var29;
         CAN_TYPE_ID var144 = new CAN_TYPE_ID("PEUGEOT_NO_USE4", 124);
         PEUGEOT_NO_USE4 = var144;
         CAN_TYPE_ID var36 = new CAN_TYPE_ID("PEUGEOT_NO_USE5", 125);
         PEUGEOT_NO_USE5 = var36;
         CAN_TYPE_ID var51 = new CAN_TYPE_ID("PEUGEOT_NO_USE6", 126);
         PEUGEOT_NO_USE6 = var51;
         CAN_TYPE_ID var193 = new CAN_TYPE_ID("PEUGEOT_NO_USE7", 127);
         PEUGEOT_NO_USE7 = var193;
         CAN_TYPE_ID var137 = new CAN_TYPE_ID("PEUGEOT_NO_USE8", 128);
         PEUGEOT_NO_USE8 = var137;
         CAN_TYPE_ID var247 = new CAN_TYPE_ID("PEUGEOT_NO_USE9", 129);
         PEUGEOT_NO_USE9 = var247;
         CAN_TYPE_ID var174 = new CAN_TYPE_ID("PEUGEOT_NO_USE10", 130);
         PEUGEOT_NO_USE10 = var174;
         CAN_TYPE_ID var201 = new CAN_TYPE_ID("MAZDA_6_CX5_2013_SIMPLE", 131);
         MAZDA_6_CX5_2013_SIMPLE = var201;
         CAN_TYPE_ID var83 = new CAN_TYPE_ID("MAZDA_6_2017_SIMPLE", 132);
         MAZDA_6_2017_SIMPLE = var83;
         CAN_TYPE_ID var98 = new CAN_TYPE_ID("MAZDA_6_2010_XINBAS", 133);
         MAZDA_6_2010_XINBAS = var98;
         CAN_TYPE_ID var192 = new CAN_TYPE_ID("MAZDA_3_MAZDA_6_2017_XINBAS", 134);
         MAZDA_3_MAZDA_6_2017_XINBAS = var192;
         CAN_TYPE_ID var145 = new CAN_TYPE_ID("MAZDA6_2010_HIWORLD", 135);
         MAZDA6_2010_HIWORLD = var145;
         CAN_TYPE_ID var42 = new CAN_TYPE_ID("PEUGEOT_NO_USE02", 136);
         PEUGEOT_NO_USE02 = var42;
         CAN_TYPE_ID var3 = new CAN_TYPE_ID("PEUGEOT_NO_USE03", 137);
         PEUGEOT_NO_USE03 = var3;
         CAN_TYPE_ID var32 = new CAN_TYPE_ID("PEUGEOT_NO_USE04", 138);
         PEUGEOT_NO_USE04 = var32;
         CAN_TYPE_ID var22 = new CAN_TYPE_ID("PEUGEOT_NO_USE05", 139);
         PEUGEOT_NO_USE05 = var22;
         CAN_TYPE_ID var180 = new CAN_TYPE_ID("PEUGEOT_NO_USE06", 140);
         PEUGEOT_NO_USE06 = var180;
         CAN_TYPE_ID var53 = new CAN_TYPE_ID("PSA_SIMPLE", 141);
         PSA_SIMPLE = var53;
         CAN_TYPE_ID var199 = new CAN_TYPE_ID("PSA_TOUCH_AIR_SIMPLE", 142);
         PSA_TOUCH_AIR_SIMPLE = var199;
         CAN_TYPE_ID var99 = new CAN_TYPE_ID("PSA_HIWORLD", 143);
         PSA_HIWORLD = var99;
         CAN_TYPE_ID var70 = new CAN_TYPE_ID("PSA_NO_USE04", 144);
         PSA_NO_USE04 = var70;
         CAN_TYPE_ID var62 = new CAN_TYPE_ID("PSA_NO_USE05", 145);
         PSA_NO_USE05 = var62;
         CAN_TYPE_ID var165 = new CAN_TYPE_ID("PSA_NO_USE06", 146);
         PSA_NO_USE06 = var165;
         CAN_TYPE_ID var14 = new CAN_TYPE_ID("PSA_NO_USE07", 147);
         PSA_NO_USE07 = var14;
         CAN_TYPE_ID var76 = new CAN_TYPE_ID("PSA_NO_USE08", 148);
         PSA_NO_USE08 = var76;
         CAN_TYPE_ID var217 = new CAN_TYPE_ID("PSA_NO_USE09", 149);
         PSA_NO_USE09 = var217;
         CAN_TYPE_ID var116 = new CAN_TYPE_ID("PSA_NO_USE10", 150);
         PSA_NO_USE10 = var116;
         CAN_TYPE_ID var162 = new CAN_TYPE_ID("SAIL_3_HIWORLD", 151);
         SAIL_3_HIWORLD = var162;
         CAN_TYPE_ID var86 = new CAN_TYPE_ID("PROJECT_3163_KZ", 152);
         PROJECT_3163_KZ = var86;
         CAN_TYPE_ID var178 = new CAN_TYPE_ID("BENZ_B200_HIWORLD", 153);
         BENZ_B200_HIWORLD = var178;
         CAN_TYPE_ID var262 = new CAN_TYPE_ID("FIAT_DOBLO_VIAGGIO_HIWORLD", 154);
         FIAT_DOBLO_VIAGGIO_HIWORLD = var262;
         CAN_TYPE_ID var15 = new CAN_TYPE_ID("FIAT_DOBLO_SIMPLE", 155);
         FIAT_DOBLO_SIMPLE = var15;
         CAN_TYPE_ID var183 = new CAN_TYPE_ID("RENAULT_MEGANE_3_SIMPLE", 156);
         RENAULT_MEGANE_3_SIMPLE = var183;
         CAN_TYPE_ID var238 = new CAN_TYPE_ID("HONDA_RAISE", 157);
         HONDA_RAISE = var238;
         CAN_TYPE_ID var152 = new CAN_TYPE_ID("HONDA_CROSSTOUR_RAISE", 158);
         HONDA_CROSSTOUR_RAISE = var152;
         CAN_TYPE_ID var268 = new CAN_TYPE_ID("FORD_SMAX_HIWORLD", 159);
         FORD_SMAX_HIWORLD = var268;
         CAN_TYPE_ID var77 = new CAN_TYPE_ID("HONDA_ACCORD_7_CYT", 160);
         HONDA_ACCORD_7_CYT = var77;
         CAN_TYPE_ID var164 = new CAN_TYPE_ID("PSA_RAISE", 161);
         PSA_RAISE = var164;
         CAN_TYPE_ID var59 = new CAN_TYPE_ID("PSA_AC_CONTRL_RAISE", 162);
         PSA_AC_CONTRL_RAISE = var59;
         CAN_TYPE_ID var91 = new CAN_TYPE_ID("RENAULT_HIWORLD", 163);
         RENAULT_HIWORLD = var91;
         CAN_TYPE_ID var126 = new CAN_TYPE_ID("MAZDA_OLD_RAISE", 164);
         MAZDA_OLD_RAISE = var126;
         CAN_TYPE_ID var40 = new CAN_TYPE_ID("TOYOTA_BINARY", 165);
         TOYOTA_BINARY = var40;
         CAN_TYPE_ID var147 = new CAN_TYPE_ID("PEUGEOT_206_SIMPLE", 166);
         PEUGEOT_206_SIMPLE = var147;
         CAN_TYPE_ID var101 = new CAN_TYPE_ID("NEW_SAMAND_XS_SIMPLE", 167);
         NEW_SAMAND_XS_SIMPLE = var101;
         CAN_TYPE_ID var203 = new CAN_TYPE_ID("GM_HIWORLD", 168);
         GM_HIWORLD = var203;
         CAN_TYPE_ID var47 = new CAN_TYPE_ID("MALIBU_2016_HIWORLD", 169);
         MALIBU_2016_HIWORLD = var47;
         CAN_TYPE_ID var11 = new CAN_TYPE_ID("GL8_2017_HIWORLD", 170);
         GL8_2017_HIWORLD = var11;
         CAN_TYPE_ID var226 = new CAN_TYPE_ID("GL6_HIWORLD", 171);
         GL6_HIWORLD = var226;
         CAN_TYPE_ID var156 = new CAN_TYPE_ID("EXCELLE_VERANO_2015_HIWORLD", 172);
         EXCELLE_VERANO_2015_HIWORLD = var156;
         CAN_TYPE_ID var110 = new CAN_TYPE_ID("HYUNDAI_SONATA_9_2018_6_PANEL_SIMPLE", 173);
         HYUNDAI_SONATA_9_2018_6_PANEL_SIMPLE = var110;
         CAN_TYPE_ID var108 = new CAN_TYPE_ID("HYUNDAI_SONATA_9_2018_8_PANEL_SIMPLE", 174);
         HYUNDAI_SONATA_9_2018_8_PANEL_SIMPLE = var108;
         CAN_TYPE_ID var66 = new CAN_TYPE_ID("HYUNDAI_SONATA_9_2018_10_PANEL_SIMPLE", 175);
         HYUNDAI_SONATA_9_2018_10_PANEL_SIMPLE = var66;
         CAN_TYPE_ID var232 = new CAN_TYPE_ID("RENUALT_RAISE", 176);
         RENUALT_RAISE = var232;
         CAN_TYPE_ID var119 = new CAN_TYPE_ID("KOLEO_2017_RAISE", 177);
         KOLEO_2017_RAISE = var119;
         CAN_TYPE_ID var57 = new CAN_TYPE_ID("PORSCHE_2009_CAYENNE_SIMPLE", 178);
         PORSCHE_2009_CAYENNE_SIMPLE = var57;
         CAN_TYPE_ID var13 = new CAN_TYPE_ID("BENZ_SMART_SIMPLE", 179);
         BENZ_SMART_SIMPLE = var13;
         CAN_TYPE_ID var48 = new CAN_TYPE_ID("LEXUS_QIZHI_SIMPLE", 180);
         LEXUS_QIZHI_SIMPLE = var48;
         CAN_TYPE_ID var224 = new CAN_TYPE_ID("HAVAL_H3_SIMPLE", 181);
         HAVAL_H3_SIMPLE = var224;
         CAN_TYPE_ID var68 = new CAN_TYPE_ID("HONDA_CRV_HIGH_RAISE", 182);
         HONDA_CRV_HIGH_RAISE = var68;
         CAN_TYPE_ID var231 = new CAN_TYPE_ID("HONDA_CRV_LOW_RAISE", 183);
         HONDA_CRV_LOW_RAISE = var231;
         CAN_TYPE_ID var195 = new CAN_TYPE_ID("HONDA_ACCORD_8_XINBAS", 184);
         HONDA_ACCORD_8_XINBAS = var195;
         CAN_TYPE_ID var107 = new CAN_TYPE_ID("CHERY_HIWORLD", 185);
         CHERY_HIWORLD = var107;
         CAN_TYPE_ID var244 = new CAN_TYPE_ID("NISSAN_TEANA_RAISE", 186);
         NISSAN_TEANA_RAISE = var244;
         CAN_TYPE_ID var204 = new CAN_TYPE_ID("NISSAN_KRORAINA_SIMA_RAISE", 187);
         NISSAN_KRORAINA_SIMA_RAISE = var204;
         CAN_TYPE_ID var135 = new CAN_TYPE_ID("NISSAN_JUN_JUKE_RAISE", 188);
         NISSAN_JUN_JUKE_RAISE = var135;
         CAN_TYPE_ID var208 = new CAN_TYPE_ID("GEELY_RAISE", 189);
         GEELY_RAISE = var208;
         CAN_TYPE_ID var163 = new CAN_TYPE_ID("JEEP_2018_COMMANDER_RAISE", 190);
         JEEP_2018_COMMANDER_RAISE = var163;
         CAN_TYPE_ID var197 = new CAN_TYPE_ID("JEEP_2017_GRAND_CHEROKEE_RAISE", 191);
         JEEP_2017_GRAND_CHEROKEE_RAISE = var197;
         CAN_TYPE_ID var84 = new CAN_TYPE_ID("JEEP_2018_WRANGLER_RAISE", 192);
         JEEP_2018_WRANGLER_RAISE = var84;
         CAN_TYPE_ID var112 = new CAN_TYPE_ID("CHERY_RAISE", 193);
         CHERY_RAISE = var112;
         CAN_TYPE_ID var254 = new CAN_TYPE_ID("MG_RAISE", 194);
         MG_RAISE = var254;
         CAN_TYPE_ID var149 = new CAN_TYPE_ID("ROEWE_RAISE", 195);
         ROEWE_RAISE = var149;
         CAN_TYPE_ID var5 = new CAN_TYPE_ID("VOLVO_XFY", 196);
         VOLVO_XFY = var5;
         CAN_TYPE_ID var139 = new CAN_TYPE_ID("TOYOTA_VERTICAL_XFY", 197);
         TOYOTA_VERTICAL_XFY = var139;
         CAN_TYPE_ID var72 = new CAN_TYPE_ID("YQ_NEW_ENERY_OTHER", 198);
         YQ_NEW_ENERY_OTHER = var72;
         CAN_TYPE_ID var258 = new CAN_TYPE_ID("CHANGAN_BINARY", 199);
         CHANGAN_BINARY = var258;
         CAN_TYPE_ID var205 = new CAN_TYPE_ID("HONDA_ACCORD_7_WITH_AC_CTRL_CYT", 200);
         HONDA_ACCORD_7_WITH_AC_CTRL_CYT = var205;
         CAN_TYPE_ID var215 = new CAN_TYPE_ID("GETU_ELECTRIC_OTHER", 201);
         GETU_ELECTRIC_OTHER = var215;
         CAN_TYPE_ID var161 = new CAN_TYPE_ID("OLD_AUDI_A3_HIWORLD", 202);
         OLD_AUDI_A3_HIWORLD = var161;
         CAN_TYPE_ID var181 = new CAN_TYPE_ID("KIA_K5_HIGH_RUSSIA_SIMPLE", 203);
         KIA_K5_HIGH_RUSSIA_SIMPLE = var181;
         CAN_TYPE_ID var235 = new CAN_TYPE_ID("HAVAL_H6_COUPE_HIWORLD", 204);
         HAVAL_H6_COUPE_HIWORLD = var235;
         CAN_TYPE_ID var209 = new CAN_TYPE_ID("GM_MOST_MODUAL_SIMPLE", 205);
         GM_MOST_MODUAL_SIMPLE = var209;
         CAN_TYPE_ID var1 = new CAN_TYPE_ID("VW_MQB_HIWORLD", 206);
         VW_MQB_HIWORLD = var1;
         CAN_TYPE_ID var186 = new CAN_TYPE_ID("BMW_E90_E84_F35_F20_HIWORLD", 207);
         BMW_E90_E84_F35_F20_HIWORLD = var186;
         CAN_TYPE_ID var177 = new CAN_TYPE_ID("BENZ_B200_2015_VITO_HIWORLD", 208);
         BENZ_B200_2015_VITO_HIWORLD = var177;
         CAN_TYPE_ID var80 = new CAN_TYPE_ID("HONDA_ACCORD_BINARY", 209);
         HONDA_ACCORD_BINARY = var80;
         CAN_TYPE_ID var111 = new CAN_TYPE_ID("FORD_EDGE_2018_HIWORLD", 210);
         FORD_EDGE_2018_HIWORLD = var111;
         CAN_TYPE_ID var168 = new CAN_TYPE_ID("FORD_EDGE_2011_2014_EXPOLER_HIWORLD", 211);
         FORD_EDGE_2011_2014_EXPOLER_HIWORLD = var168;
         CAN_TYPE_ID var109 = new CAN_TYPE_ID("FORD_MONDEO_2013_REMOVE_AC_HIWORLD", 212);
         FORD_MONDEO_2013_REMOVE_AC_HIWORLD = var109;
         CAN_TYPE_ID var92 = new CAN_TYPE_ID("MAZDA_AXELA_HIWORLD", 213);
         MAZDA_AXELA_HIWORLD = var92;
         CAN_TYPE_ID var122 = new CAN_TYPE_ID("MAZDA_HIWORLD", 214);
         MAZDA_HIWORLD = var122;
         CAN_TYPE_ID var182 = new CAN_TYPE_ID("JEEP_COMPASS_2017_HIWORLD", 215);
         JEEP_COMPASS_2017_HIWORLD = var182;
         CAN_TYPE_ID var124 = new CAN_TYPE_ID("BUICK_ENCLAVE_HIWORLD", 216);
         BUICK_ENCLAVE_HIWORLD = var124;
         CAN_TYPE_ID var45 = new CAN_TYPE_ID("FIAT_LINEA_HIWORLD", 217);
         FIAT_LINEA_HIWORLD = var45;
         CAN_TYPE_ID var23 = new CAN_TYPE_ID("FORD_FIESTA_OLD_HIWORLD", 218);
         FORD_FIESTA_OLD_HIWORLD = var23;
         CAN_TYPE_ID var148 = new CAN_TYPE_ID("PEUGEOT_307_408_3008_RAISE", 219);
         PEUGEOT_307_408_3008_RAISE = var148;
         CAN_TYPE_ID var158 = new CAN_TYPE_ID("THRUMPCHI_RAISE", 220);
         THRUMPCHI_RAISE = var158;
         CAN_TYPE_ID var58 = new CAN_TYPE_ID("HAVAL_H2_HIWORLD", 221);
         HAVAL_H2_HIWORLD = var58;
         CAN_TYPE_ID var113 = new CAN_TYPE_ID("BESTUNE_X80_2017_RAISE", 222);
         BESTUNE_X80_2017_RAISE = var113;
         CAN_TYPE_ID var248 = new CAN_TYPE_ID("MAZDA_BT_50_SIMPLE", 223);
         MAZDA_BT_50_SIMPLE = var248;
         CAN_TYPE_ID var252 = new CAN_TYPE_ID("HONDA_ACCORD_8_HIWORLD", 224);
         HONDA_ACCORD_8_HIWORLD = var252;
         CAN_TYPE_ID var38 = new CAN_TYPE_ID("HONDA_ACCORD_7_DOGEN", 225);
         HONDA_ACCORD_7_DOGEN = var38;
         CAN_TYPE_ID var95 = new CAN_TYPE_ID("MAZDA_6_XINBAS", 226);
         MAZDA_6_XINBAS = var95;
         CAN_TYPE_ID var33 = new CAN_TYPE_ID("AT360_OTHER", 227);
         AT360_OTHER = var33;
         CAN_TYPE_ID var20 = new CAN_TYPE_ID("SENOVA_D60_BEIJING_BJ20_OUDI", 228);
         SENOVA_D60_BEIJING_BJ20_OUDI = var20;
         CAN_TYPE_ID var259 = new CAN_TYPE_ID("BEIJING_BJ40_OUDI", 229);
         BEIJING_BJ40_OUDI = var259;
         CAN_TYPE_ID var134 = new CAN_TYPE_ID("SENOVA_X25_X55_OUDI", 230);
         SENOVA_X25_X55_OUDI = var134;
         CAN_TYPE_ID var141 = new CAN_TYPE_ID("SENOVA_X35_CHANGHE_Q35_OUDI", 231);
         SENOVA_X35_CHANGHE_Q35_OUDI = var141;
         CAN_TYPE_ID var90 = new CAN_TYPE_ID("WEIWANG_M50F_OUDI", 232);
         WEIWANG_M50F_OUDI = var90;
         CAN_TYPE_ID var179 = new CAN_TYPE_ID("HAVAL_H6_HIWORLD", 233);
         HAVAL_H6_HIWORLD = var179;
         CAN_TYPE_ID var0 = new CAN_TYPE_ID("BENZ_B200_LUZHENG", 234);
         BENZ_B200_LUZHENG = var0;
         CAN_TYPE_ID var82 = new CAN_TYPE_ID("MAZDA_6_LUZHENG", 235);
         MAZDA_6_LUZHENG = var82;
         CAN_TYPE_ID var46 = new CAN_TYPE_ID("SHANGQI_DATONG_RAISE", 236);
         SHANGQI_DATONG_RAISE = var46;
         CAN_TYPE_ID var105 = new CAN_TYPE_ID("HANTENG_RAISE", 237);
         HANTENG_RAISE = var105;
         CAN_TYPE_ID var221 = new CAN_TYPE_ID("HANTENG_X7_RAISE", 238);
         HANTENG_X7_RAISE = var221;
         CAN_TYPE_ID var102 = new CAN_TYPE_ID("HAIMA_RAISE", 239);
         HAIMA_RAISE = var102;
         CAN_TYPE_ID var41 = new CAN_TYPE_ID("HAIMA_S7_S5_FAMILY_RAISE", 240);
         HAIMA_S7_S5_FAMILY_RAISE = var41;
         CAN_TYPE_ID var43 = new CAN_TYPE_ID("BISU_M3_T3_RAISE", 241);
         BISU_M3_T3_RAISE = var43;
         CAN_TYPE_ID var218 = new CAN_TYPE_ID("HAIMA_M8_RAISE", 242);
         HAIMA_M8_RAISE = var218;
         CAN_TYPE_ID var63 = new CAN_TYPE_ID("DONGNAN_V5_RAISE", 243);
         DONGNAN_V5_RAISE = var63;
         CAN_TYPE_ID var64 = new CAN_TYPE_ID("DONGFENG_JINGYI_X5_RAISE", 244);
         DONGFENG_JINGYI_X5_RAISE = var64;
         CAN_TYPE_ID var115 = new CAN_TYPE_ID("FABBRICA_RAISE", 245);
         FABBRICA_RAISE = var115;
         CAN_TYPE_ID var30 = new CAN_TYPE_ID("BMW5_2E_RAISE", 246);
         BMW5_2E_RAISE = var30;
         CAN_TYPE_ID var234 = new CAN_TYPE_ID("BAIC_WEIWANG_M20_RAISE", 247);
         BAIC_WEIWANG_M20_RAISE = var234;
         CAN_TYPE_ID var96 = new CAN_TYPE_ID("TRUMPCHI_HIWORLD", 248);
         TRUMPCHI_HIWORLD = var96;
         CAN_TYPE_ID var97 = new CAN_TYPE_ID("FENGGUANG_RAISE", 249);
         FENGGUANG_RAISE = var97;
         CAN_TYPE_ID var56 = new CAN_TYPE_ID("DONGFENG_FENGSHEN_RAISE", 250);
         DONGFENG_FENGSHEN_RAISE = var56;
         CAN_TYPE_ID var210 = new CAN_TYPE_ID("DONGFENG_FENGGUANG_50_RAISE", 251);
         DONGFENG_FENGGUANG_50_RAISE = var210;
         CAN_TYPE_ID var230 = new CAN_TYPE_ID("DONGFENG_FENGGUANG_580_18_RAISE", 252);
         DONGFENG_FENGGUANG_580_18_RAISE = var230;
         CAN_TYPE_ID var176 = new CAN_TYPE_ID("BAIC_SHENBAO_RAISE", 253);
         BAIC_SHENBAO_RAISE = var176;
         CAN_TYPE_ID var251 = new CAN_TYPE_ID("MAZDA_BINARY", 254);
         MAZDA_BINARY = var251;
         CAN_TYPE_ID var237 = new CAN_TYPE_ID("BAOJ_RAISE", 255);
         BAOJ_RAISE = var237;
         CAN_TYPE_ID var60 = new CAN_TYPE_ID("MAZDA_RAISE", 256);
         MAZDA_RAISE = var60;
         CAN_TYPE_ID var142 = new CAN_TYPE_ID("GEELY_GC7_HIWORLD", 257);
         GEELY_GC7_HIWORLD = var142;
         CAN_TYPE_ID var261 = new CAN_TYPE_ID("GEELY_VISION_HIWORLD", 258);
         GEELY_VISION_HIWORLD = var261;
         CAN_TYPE_ID var225 = new CAN_TYPE_ID("GEELY_GL_GS_HIWORLD", 259);
         GEELY_GL_GS_HIWORLD = var225;
         CAN_TYPE_ID var239 = new CAN_TYPE_ID("RENAULT_KOLEOS2_AIR_AUTO_SIMPLE", 260);
         RENAULT_KOLEOS2_AIR_AUTO_SIMPLE = var239;
         CAN_TYPE_ID var39 = new CAN_TYPE_ID("RENAULT_KOLEOS2_AIR_MANUAL_SIMPLE", 261);
         RENAULT_KOLEOS2_AIR_MANUAL_SIMPLE = var39;
         CAN_TYPE_ID var6 = new CAN_TYPE_ID("FIAT_VIAGGIO_SIMPLE", 262);
         FIAT_VIAGGIO_SIMPLE = var6;
         CAN_TYPE_ID var194 = new CAN_TYPE_ID("NEW_PEUGEOT_206_SIMPLE", 263);
         NEW_PEUGEOT_206_SIMPLE = var194;
         CAN_TYPE_ID var219 = new CAN_TYPE_ID("AUDI_Q3_RAISE", 264);
         AUDI_Q3_RAISE = var219;
         CAN_TYPE_ID var74 = new CAN_TYPE_ID("BENZ_RAISE", 265);
         BENZ_RAISE = var74;
         CAN_TYPE_ID var120 = new CAN_TYPE_ID("CMC_H3_V3_HIWORLD", 266);
         CMC_H3_V3_HIWORLD = var120;
         CAN_TYPE_ID var207 = new CAN_TYPE_ID("ACCORD_8_OUDI", 267);
         ACCORD_8_OUDI = var207;
         CAN_TYPE_ID var71 = new CAN_TYPE_ID("JEEP_OTHER", 268);
         JEEP_OTHER = var71;
         $VALUES = new CAN_TYPE_ID[]{var264, var211, var54, var103, var171, var127, var27, var190, var228, var242, var241, var166, var136, var157, var131, var31, var24, var123, var25, var206, var132, var7, var93, var138, var21, var198, var75, var133, var128, var87, var222, var28, var88, var143, var79, var4, var35, var52, var8, var169, var85, var37, var256, var81, var216, var266, var146, var114, var267, var212, var257, var150, var167, var265, var69, var9, var12, var188, var184, var130, var160, var140, var240, var263, var121, var246, var100, var151, var187, var117, var214, var104, var19, var173, var260, var249, var73, var233, var250, var10, var44, var213, var175, var55, var159, var26, var16, var67, var245, var65, var243, var2, var129, var18, var191, var118, var153, var89, var189, var227, var154, var106, var253, var236, var170, var34, var202, var223, var185, var196, var17, var94, var125, var229, var200, var61, var49, var172, var220, var78, var50, var255, var155, var29, var144, var36, var51, var193, var137, var247, var174, var201, var83, var98, var192, var145, var42, var3, var32, var22, var180, var53, var199, var99, var70, var62, var165, var14, var76, var217, var116, var162, var86, var178, var262, var15, var183, var238, var152, var268, var77, var164, var59, var91, var126, var40, var147, var101, var203, var47, var11, var226, var156, var110, var108, var66, var232, var119, var57, var13, var48, var224, var68, var231, var195, var107, var244, var204, var135, var208, var163, var197, var84, var112, var254, var149, var5, var139, var72, var258, var205, var215, var161, var181, var235, var209, var1, var186, var177, var80, var111, var168, var109, var92, var122, var182, var124, var45, var23, var148, var158, var58, var113, var248, var252, var38, var95, var33, var20, var259, var134, var141, var90, var179, var0, var82, var46, var105, var221, var102, var41, var43, var218, var63, var64, var115, var30, var234, var96, var97, var56, var210, var230, var176, var251, var237, var60, var142, var261, var225, var239, var39, var6, var194, var219, var74, var120, var207, var71};
      }

      public int getStringId(Context var1) {
         return var1.getResources().getIdentifier(this.toString(), "string", var1.getPackageName());
      }
   }

   public static enum ENUM_CANBUS_SUPPLIER {
      private static final ENUM_CANBUS_SUPPLIER[] $VALUES;
      CAN_SUPP_ALL,
      CAN_SUPP_BINARY,
      CAN_SUPP_CYT,
      CAN_SUPP_DOGEN,
      CAN_SUPP_HIWORLD,
      CAN_SUPP_LUZHENG,
      CAN_SUPP_OTHER,
      CAN_SUPP_OUDI,
      CAN_SUPP_RAISE,
      CAN_SUPP_SIMPLE,
      CAN_SUPP_XFY,
      CAN_SUPP_XINBAS;

      static {
         ENUM_CANBUS_SUPPLIER var5 = new ENUM_CANBUS_SUPPLIER("CAN_SUPP_ALL", 0);
         CAN_SUPP_ALL = var5;
         ENUM_CANBUS_SUPPLIER var4 = new ENUM_CANBUS_SUPPLIER("CAN_SUPP_SIMPLE", 1);
         CAN_SUPP_SIMPLE = var4;
         ENUM_CANBUS_SUPPLIER var7 = new ENUM_CANBUS_SUPPLIER("CAN_SUPP_XINBAS", 2);
         CAN_SUPP_XINBAS = var7;
         ENUM_CANBUS_SUPPLIER var8 = new ENUM_CANBUS_SUPPLIER("CAN_SUPP_RAISE", 3);
         CAN_SUPP_RAISE = var8;
         ENUM_CANBUS_SUPPLIER var6 = new ENUM_CANBUS_SUPPLIER("CAN_SUPP_HIWORLD", 4);
         CAN_SUPP_HIWORLD = var6;
         ENUM_CANBUS_SUPPLIER var11 = new ENUM_CANBUS_SUPPLIER("CAN_SUPP_CYT", 5);
         CAN_SUPP_CYT = var11;
         ENUM_CANBUS_SUPPLIER var10 = new ENUM_CANBUS_SUPPLIER("CAN_SUPP_BINARY", 6);
         CAN_SUPP_BINARY = var10;
         ENUM_CANBUS_SUPPLIER var9 = new ENUM_CANBUS_SUPPLIER("CAN_SUPP_XFY", 7);
         CAN_SUPP_XFY = var9;
         ENUM_CANBUS_SUPPLIER var2 = new ENUM_CANBUS_SUPPLIER("CAN_SUPP_DOGEN", 8);
         CAN_SUPP_DOGEN = var2;
         ENUM_CANBUS_SUPPLIER var3 = new ENUM_CANBUS_SUPPLIER("CAN_SUPP_OUDI", 9);
         CAN_SUPP_OUDI = var3;
         ENUM_CANBUS_SUPPLIER var0 = new ENUM_CANBUS_SUPPLIER("CAN_SUPP_LUZHENG", 10);
         CAN_SUPP_LUZHENG = var0;
         ENUM_CANBUS_SUPPLIER var1 = new ENUM_CANBUS_SUPPLIER("CAN_SUPP_OTHER", 11);
         CAN_SUPP_OTHER = var1;
         $VALUES = new ENUM_CANBUS_SUPPLIER[]{var5, var4, var7, var8, var6, var11, var10, var9, var2, var3, var0, var1};
      }

      public int getStringId(Context var1) {
         return var1.getResources().getIdentifier(this.toString(), "string", var1.getPackageName());
      }
   }

   public static enum ENUM_CANSBUS_HIWORLD_MEDIA_TYPE {
      private static final ENUM_CANSBUS_HIWORLD_MEDIA_TYPE[] $VALUES;
      A2DP,
      AM1,
      AM2,
      AUX,
      CAMERA,
      CD,
      DVD,
      DVDC,
      FM1,
      FM2,
      FM3,
      IPOD,
      MCARD,
      NAVI,
      NO_USE1,
      NO_USE2,
      NO_USE3,
      OFF,
      PHONE,
      TV,
      USB,
      USB_VID;

      static {
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var2 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("OFF", 0);
         OFF = var2;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var10 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("FM1", 1);
         FM1 = var10;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var12 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("FM2", 2);
         FM2 = var12;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var15 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("FM3", 3);
         FM3 = var15;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var16 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("AM1", 4);
         AM1 = var16;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var20 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("AM2", 5);
         AM2 = var20;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var21 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("CD", 6);
         CD = var21;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var0 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("DVD", 7);
         DVD = var0;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var8 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("TV", 8);
         TV = var8;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var9 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("NAVI", 9);
         NAVI = var9;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var11 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("PHONE", 10);
         PHONE = var11;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var17 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("IPOD", 11);
         IPOD = var17;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var13 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("AUX", 12);
         AUX = var13;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var19 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("USB", 13);
         USB = var19;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var3 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("MCARD", 14);
         MCARD = var3;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var1 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("DVDC", 15);
         DVDC = var1;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var14 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("CAMERA", 16);
         CAMERA = var14;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var6 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("NO_USE1", 17);
         NO_USE1 = var6;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var5 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("NO_USE2", 18);
         NO_USE2 = var5;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var7 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("NO_USE3", 19);
         NO_USE3 = var7;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var18 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("A2DP", 20);
         A2DP = var18;
         ENUM_CANSBUS_HIWORLD_MEDIA_TYPE var4 = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE("USB_VID", 21);
         USB_VID = var4;
         $VALUES = new ENUM_CANSBUS_HIWORLD_MEDIA_TYPE[]{var2, var10, var12, var15, var16, var20, var21, var0, var8, var9, var11, var17, var13, var19, var3, var1, var14, var6, var5, var7, var18, var4};
      }
   }

   public static enum ENUM_CANSBUS_SIMPLE_MEDIA_TYPE {
      private static final ENUM_CANSBUS_SIMPLE_MEDIA_TYPE[] $VALUES;
      A2DP,
      ATV,
      AUX,
      CD,
      CDC,
      DISC,
      DTV,
      DVD,
      IPOD,
      MY_MUSIC,
      NAVI,
      OFF,
      OTHER,
      PHONE,
      RADIO,
      SD,
      USB,
      USB_VIDEO,
      XM;

      static {
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var3 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("OFF", 0);
         OFF = var3;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var1 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("RADIO", 1);
         RADIO = var1;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var16 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("DISC", 2);
         DISC = var16;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var5 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("ATV", 3);
         ATV = var5;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var9 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("NAVI", 4);
         NAVI = var9;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var13 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("PHONE", 5);
         PHONE = var13;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var17 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("IPOD", 6);
         IPOD = var17;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var7 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("AUX", 7);
         AUX = var7;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var8 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("USB", 8);
         USB = var8;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var14 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("SD", 9);
         SD = var14;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var11 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("DTV", 10);
         DTV = var11;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var4 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("A2DP", 11);
         A2DP = var4;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var2 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("OTHER", 12);
         OTHER = var2;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var12 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("CDC", 13);
         CDC = var12;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var6 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("CD", 14);
         CD = var6;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var18 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("DVD", 15);
         DVD = var18;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var0 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("USB_VIDEO", 16);
         USB_VIDEO = var0;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var15 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("MY_MUSIC", 17);
         MY_MUSIC = var15;
         ENUM_CANSBUS_SIMPLE_MEDIA_TYPE var10 = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE("XM", 18);
         XM = var10;
         $VALUES = new ENUM_CANSBUS_SIMPLE_MEDIA_TYPE[]{var3, var1, var16, var5, var9, var13, var17, var7, var8, var14, var11, var4, var2, var12, var6, var18, var0, var15, var10};
      }
   }

   public static enum ENUM_CANSBUS_XINBAS_MEDIA_TYPE {
      private static final ENUM_CANSBUS_XINBAS_MEDIA_TYPE[] $VALUES;
      MID_A2DP,
      MID_AUX,
      MID_CDC,
      MID_DISC,
      MID_DVR,
      MID_IPOD,
      MID_NAVI,
      MID_OFF,
      MID_OTHER,
      MID_PHONE,
      MID_RADIO,
      MID_SD,
      MID_TV,
      MID_USB,
      MID_VOL;

      static {
         ENUM_CANSBUS_XINBAS_MEDIA_TYPE var6 = new ENUM_CANSBUS_XINBAS_MEDIA_TYPE("MID_OFF", 0);
         MID_OFF = var6;
         ENUM_CANSBUS_XINBAS_MEDIA_TYPE var2 = new ENUM_CANSBUS_XINBAS_MEDIA_TYPE("MID_RADIO", 1);
         MID_RADIO = var2;
         ENUM_CANSBUS_XINBAS_MEDIA_TYPE var13 = new ENUM_CANSBUS_XINBAS_MEDIA_TYPE("MID_DISC", 2);
         MID_DISC = var13;
         ENUM_CANSBUS_XINBAS_MEDIA_TYPE var10 = new ENUM_CANSBUS_XINBAS_MEDIA_TYPE("MID_TV", 3);
         MID_TV = var10;
         ENUM_CANSBUS_XINBAS_MEDIA_TYPE var5 = new ENUM_CANSBUS_XINBAS_MEDIA_TYPE("MID_NAVI", 4);
         MID_NAVI = var5;
         ENUM_CANSBUS_XINBAS_MEDIA_TYPE var0 = new ENUM_CANSBUS_XINBAS_MEDIA_TYPE("MID_PHONE", 5);
         MID_PHONE = var0;
         ENUM_CANSBUS_XINBAS_MEDIA_TYPE var8 = new ENUM_CANSBUS_XINBAS_MEDIA_TYPE("MID_IPOD", 6);
         MID_IPOD = var8;
         ENUM_CANSBUS_XINBAS_MEDIA_TYPE var3 = new ENUM_CANSBUS_XINBAS_MEDIA_TYPE("MID_AUX", 7);
         MID_AUX = var3;
         ENUM_CANSBUS_XINBAS_MEDIA_TYPE var1 = new ENUM_CANSBUS_XINBAS_MEDIA_TYPE("MID_USB", 8);
         MID_USB = var1;
         ENUM_CANSBUS_XINBAS_MEDIA_TYPE var11 = new ENUM_CANSBUS_XINBAS_MEDIA_TYPE("MID_SD", 9);
         MID_SD = var11;
         ENUM_CANSBUS_XINBAS_MEDIA_TYPE var4 = new ENUM_CANSBUS_XINBAS_MEDIA_TYPE("MID_A2DP", 10);
         MID_A2DP = var4;
         ENUM_CANSBUS_XINBAS_MEDIA_TYPE var9 = new ENUM_CANSBUS_XINBAS_MEDIA_TYPE("MID_DVR", 11);
         MID_DVR = var9;
         ENUM_CANSBUS_XINBAS_MEDIA_TYPE var12 = new ENUM_CANSBUS_XINBAS_MEDIA_TYPE("MID_CDC", 12);
         MID_CDC = var12;
         ENUM_CANSBUS_XINBAS_MEDIA_TYPE var7 = new ENUM_CANSBUS_XINBAS_MEDIA_TYPE("MID_VOL", 13);
         MID_VOL = var7;
         ENUM_CANSBUS_XINBAS_MEDIA_TYPE var14 = new ENUM_CANSBUS_XINBAS_MEDIA_TYPE("MID_OTHER", 14);
         MID_OTHER = var14;
         $VALUES = new ENUM_CANSBUS_XINBAS_MEDIA_TYPE[]{var6, var2, var13, var10, var5, var0, var8, var3, var1, var11, var4, var9, var12, var7, var14};
      }
   }
}
