package com.hzbhd.commontools;

import java.util.HashMap;

public class DefaultAppId {
   public static HashMap service = new HashMap() {
      {
         this.put(AppIdDef.APP_ID.BHD_SERVICE_SETTINGS, new ComponentName("com.hzbhd.service.setting", "com.hzbhd.setting.service.SettingMidwareService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_KEY, new ComponentName("com.hzbhd.service.keydispatcher", "com.hzbhd.service.keydispatcher.KeyDispatcherMidwareService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_SOURCE, new ComponentName("com.hzbhd.service.sourcemanager", "com.hzbhd.service.sourcemanager.SourceMidwareService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_HARDWARE, new ComponentName("com.hzbhd.service.hardware", "com.hzbhd.service.hardware.HardwareService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_FRAMEWORK, new ComponentName("com.hzbhd.service.framework", "com.hzbhd.service.framework.FrameworkService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_MCU, new ComponentName("com.hzbhd.service.mcu", "com.hzbhd.service.mcu.service.MCUMainService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_AUDIO, new ComponentName("com.hzbhd.service.audio", "com.hzbhd.service.audio.AudioService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_CAMERA, new ComponentName("com.hzbhd.service.camera", "com.hzbhd.service.camera.CameraService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_MEDIA_SCANNER, new ComponentName("com.hzbhd.service.mediascanner", "com.hzbhd.service.mediascanner.RunService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_MEDIA, new ComponentName("com.hzbhd.service.media", "com.hzbhd.service.media.MediaService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_BLUETOOTH, new ComponentName("com.hzbhd.service.bluetooth", "com.hzbhd.service.bluetooth.impl.services.BTMiddleService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_MISC, new ComponentName("com.hzbhd.ui.misc", "com.hzbhd.ui.service.MiscService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_CANBUS, new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.CanbusMsgService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_AUTO, new ComponentName("com.hzbhd.androidauto", "com.hzbhd.androidauto.AAService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_CARPLAY, new ComponentName("com.hzbhd.carplay", "com.hzbhd.carplay.service.CarPlayService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_LOG, new ComponentName("com.hzbhd.ui.log", "com.hzbhd.ui.service.LogService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_INIT, new ComponentName("com.hzbhd.ui.misc", "com.hzbhd.ui.init.service.InitService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_DISC, new ComponentName("com.hzbhd.service.disc", "com.hzbhd.service.disc.DiscService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_SPEECH, new ComponentName("com.hzbhd.speechrecognition", "com.hzbhd.speechrecognition.txz.BhdTxzService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_SPEECH_LYRA, new ComponentName("com.aispeech.lyra.adapter", "com.aispeech.lyra.adapter.bhd.BodaService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_TXZ_MS, new ComponentName("com.hzbhd.bhdtxzoladapter", "com.hzbhd.bhdtxzoladapter.BodaService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_DAB, new ComponentName("com.hzbhd.service.dab", "com.hzbhd.service.dab.DabService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_DVR, new ComponentName("com.hzbhd.service.dvr", "com.hzbhd.service.dvr.DvrService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_LCD, new ComponentName("com.hzbhd.service.lcd", "com.hzbhd.service.lcd.LcdService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_GYROSCOPE, new ComponentName("com.hzbhd.service.gyroscope", "com.hzbhd.service.gyroscope.GyroscopeService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_UPGRADE, new ComponentName("com.hzbhd.service.upgrade", "com.hzbhd.service.upgrade.UpgradeService"));
         this.put(AppIdDef.APP_ID.MS_SJS_360_DEAMON, new ComponentName("com.sjs.truckdeamon", "com.sjs.truckdeamon.services.DeamonService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_LCMCUCONFIG, new ComponentName("com.mcuconfig.service", "com.mcuconfig.service.McuConfigService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_LCBLUETOOTH, new ComponentName("com.bluetooth.service", "com.bluetooth.service.BTMiddleService"));
         this.put(AppIdDef.APP_ID.BHD_SERVICE_SIRIUS_XM, new ComponentName("com.hzbhd.siriusxm.ui", "com.hzbhd.siriusxm.ui.service.SiriusXMService"));
      }
   };
   public static HashMap ui = new HashMap() {
      {
         this.put(AppIdDef.APP_ID.BHD_NONE, new ComponentName("", ""));
         this.put(AppIdDef.APP_ID.BHD_UI_HDMI, new ComponentName("com.hzbhd.ui.camera", "com.hzbhd.ui.activity.HdmiActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_DTV, new ComponentName("com.hzbhd.ui.camera", "com.hzbhd.ui.activity.DtvActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_AUX, new ComponentName("com.hzbhd.ui.camera", "com.hzbhd.ui.activity.AuxInActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_DISC, new ComponentName("com.hzbhd.ui.media", "com.hzbhd.ui.activity.DiscActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_F_CAMERA, new ComponentName("com.hzbhd.ui.camera", "com.hzbhd.ui.activity.FCameraActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_4_CAMERA, new ComponentName("com.hzbhd.ui.camera", "com.hzbhd.ui.activity.Camera4Activity"));
         this.put(AppIdDef.APP_ID.BHD_UI_LAUNCHER_NAVI, new ComponentName("com.android.launcher3", "com.android.launcher3.firstscreen.NaviActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_RADIO, new ComponentName("com.hzbhd.radioui", "com.hzbhd.radioui.RadioMainActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_MUSIC, new ComponentName("com.hzbhd.ui.media", "com.hzbhd.ui.activity.MusicActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_VIDEO, new ComponentName("com.hzbhd.ui.media", "com.hzbhd.ui.activity.VideoActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_IMAGE, new ComponentName("com.hzbhd.ui.media", "com.hzbhd.ui.activity.ImageActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_BT_PHONE, new ComponentName("com.hzbhd.btui", "com.hzbhd.btui.HfpMainActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_BT_MUSIC, new ComponentName("com.hzbhd.btui", "com.hzbhd.btui.A2dpMainActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_BT_BUBBLE_CALL, new ComponentName("com.hzbhd.btui", "com.hzbhd.btui.service.BubbleCall"));
         this.put(AppIdDef.APP_ID.BHD_UI_DSP, new ComponentName("com.hzbhd.ui.dsp", "com.hzbhd.ui.activity.DspActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_DAB_HGJ, new ComponentName("com.hzbhd.dab.hgj", "com.hzbhd.dab.MainActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_DAB_YHX, new ComponentName("com.hzbhd.dab.yhx", "com.hzbhd.dab.YhxMainActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_DAB_NX3K, new ComponentName("com.hzbhd.dab.nx3k", "com.hzbhd.ui.activity.DabActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_FAQ, new ComponentName("com.handbook", "com.artifex.mupdfdemo.main.MuPDFActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_FAQ_HY, new ComponentName("com.hzbhd.handbook", "com.artifex.mupdfdemo.main.MuPDFActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_FAQ_HY_F5, new ComponentName("com.hzbhd.handbook", "com.artifex.mupdfdemo.MuPDFActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_LINK, new ComponentName("com.hzbhd.phonelink", "com.hzbhd.phonelink.WelcomeActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_CAN_BUS, new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.activity.MainActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_SETTINGS, new ComponentName("com.hzbhd.carsettings", "com.hzbhd.carsettings.activity.MainActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_MODEN_CALL, new ComponentName("com.hzbhd.ui.modem.call", "com.hzbhd.ui.modem.call.MainActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_CARPLAY, new ComponentName("com.hzbhd.phonelink", "com.hzbhd.phonelink.carplay.CarPlayWelcomeActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_AUTO, new ComponentName("com.hzbhd.phonelink", "com.hzbhd.phonelink.auto.AutoWelcomeActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_CARPLAY_Not, new ComponentName("com.hzbhd.phonelink", "com.hzbhd.phonelink.carplay.CarPlayWelcomeAct;ivity_not_conn"));
         this.put(AppIdDef.APP_ID.BHD_UI_AUTO_Not, new ComponentName("com.hzbhd.phonelink", "com.hzbhd.phonelink.auto.AutoWelcomeActivity_not;_conn"));
         this.put(AppIdDef.APP_ID.BHD_UI_CONNECTIONS, new ComponentName("com.hzbhd.phonelink", "com.hzbhd.phonelink.WelcomeActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_UPGRADE, new ComponentName("com.baidu.ota", "com.baidu.ota.activity.LaunchActivity"));
         this.put(AppIdDef.APP_ID.WIRELESS_Q_LINK, new ComponentName("com.example.carlink.autoplay", "com.example.carlink.autoplay.MainActivity"));
         this.put(AppIdDef.APP_ID.BHD_UI_SIRIUS_XM, new ComponentName("com.hzbhd.siriusxm.ui", "com.hzbhd.siriusxm.ui.SiriusXMActivity"));
         this.put(AppIdDef.APP_ID.BHD_XYQ_AVM, new ComponentName("com.ivicar.avm", "com.ivicar.modules.main.view.MainActivity"));
         this.put(AppIdDef.APP_ID.BHD_XYQ_AVM_CAMERA4, new ComponentName("com.ivicar.avm", "com.ivicar.modules.calibrate.view.CalibrateActivity2"));
         this.put(AppIdDef.APP_ID.AUTOCHIP_AVM, new ComponentName("com.autochips.avmplayer", "com.autochips.avmplayer.SurroundViewActivity"));
         this.put(AppIdDef.APP_ID.GOOGLE_MAP, new ComponentName("com.google.android.apps.maps", "com.google.android.maps.MapsActivity"));
         this.put(AppIdDef.APP_ID.GOOGLE_EMAIL, new ComponentName("com.android.email", "com.android.email.activity.Welcome"));
         this.put(AppIdDef.APP_ID.GOOGLE_SEARCH, new ComponentName("com.google.android.googlequicksearchbox", "com.google.android.googlequicksearchbox.SearchActivity"));
         this.put(AppIdDef.APP_ID.GOOGLE_YOUTUBE, new ComponentName("com.google.android.youtube", "com.google.android.youtube.app.honeycomb.Shell$HomeActivity"));
         this.put(AppIdDef.APP_ID.GOOGLE_CHROME, new ComponentName("com.android.chrome", "com.google.android.apps.chrome.Main"));
         this.put(AppIdDef.APP_ID.GOOGLE_PLAY_STORE, new ComponentName("com.android.vending", "com.android.vending.AssetBrowserActivity"));
         this.put(AppIdDef.APP_ID.GOOGLE_TTS, new ComponentName("com.google.android.tts", ""));
         this.put(AppIdDef.APP_ID.GOOGLE_SERVICES_FRAMEWORK, new ComponentName("com.google.android.gsf", ""));
         this.put(AppIdDef.APP_ID.GOOGLE_GMS_CORE, new ComponentName("com.google.android.gms", "com.google.android.gms.app.settings.GoogleSettingsActivity"));
         this.put(AppIdDef.APP_ID.ANDROID_SOUND_RECORDER, new ComponentName("com.android.soundrecorder", "com.android.soundrecorder.SoundRecorder"));
         this.put(AppIdDef.APP_ID.ANDROID_FILE_EXPLORE, new ComponentName("com.android.documentsui", "com.android.documentsui.LauncherActivity"));
         this.put(AppIdDef.APP_ID.ANDROID_CALCULATOR, new ComponentName("com.android.calculator2", "com.android.calculator2.Calculator"));
         this.put(AppIdDef.APP_ID.ANDROID_WebView, new ComponentName("com.android.webview", "com.android.webview.chromium.LicenseActivity"));
         this.put(AppIdDef.APP_ID.ANDROID_Dialor, new ComponentName("com.android.dialer", "com.android.dialer.app.DialtactsActivity"));
         this.put(AppIdDef.APP_ID.ORHER_GPSTEST, new ComponentName("com.chartcross.gpstestplus", "com.chartcross.gpstestplus.GPSTestPlus"));
         this.put(AppIdDef.APP_ID.OTHER_EASYCONN, new ComponentName("net.easyconn", "net.easyconn.ui.Bhd07MainActivity"));
         this.put(AppIdDef.APP_ID.OTHER_EASYCONN_MS, new ComponentName("net.easyconn", "net.easyconn.ui.StandMainActivity"));
         this.put(AppIdDef.APP_ID.OTHER_EASYCONN_MS2, new ComponentName("net.easyconn", "net.easyconn.ui.Mskj02MainActivity"));
         this.put(AppIdDef.APP_ID.OTHER_ZEROTIER, new ComponentName("com.zerotier.one", "com.zerotier.one.ui.NetworkListActivity"));
         this.put(AppIdDef.APP_ID.OTHER_ES_EXPLORE, new ComponentName("com.estrongs.android.pop", "com.estrongs.android.pop.view.FileExplorerActivity"));
         this.put(AppIdDef.APP_ID.OTHER_SPOTIFY, new ComponentName("com.spotify.music", "com.spotify.music.MainActivity"));
         this.put(AppIdDef.APP_ID.OTHER_KUWO, new ComponentName("cn.kuwo.kwmusiccar", "cn.kuwo.kwmusiccar.WelcomeActivity"));
         this.put(AppIdDef.APP_ID.OTHER_XIMALAYA, new ComponentName("com.ximalaya.ting.android.car", "com.ximalaya.ting.android.car.business.module.splash.WelActivity"));
         this.put(AppIdDef.APP_ID.OTHER_TXZ, new ComponentName("com.txznet.adapter", "com.txznet.adapter.ui.MainActivity"));
         this.put(AppIdDef.APP_ID.MS_SANY_KC, new ComponentName("com.sany.ore", "com.sany.ore.SplashActivity"));
         this.put(AppIdDef.APP_ID.MS_HANDBOOK_KS, new ComponentName("com.hzbhd.handbook.kuangshan", "com.artifex.mupdfdemo.main.MuPDFActivity"));
         this.put(AppIdDef.APP_ID.MS_HANDBOOK_UPKEEP, new ComponentName("com.hzbhd.handbook.upkeep", "com.artifex.mupdfdemo.main.MuPDFActivity"));
         this.put(AppIdDef.APP_ID.MS_SJS_360, new ComponentName("com.sjs.truckbsd", "com.sjs.truckbsd.Main2Activity"));
         this.put(AppIdDef.APP_ID.NAVI_WAZE, new ComponentName("com.waze", "com.waze.FreeMapAppActivity"));
         this.put(AppIdDef.APP_ID.MO_JI, new ComponentName("com.moji.mjweather", "com.moji.mjweather.LauncherActivity"));
         this.put(AppIdDef.APP_ID.D1_LINK, new ComponentName("net.easyconn", "net.easyconn.ui.Bhd08MainActivity"));
         this.put(AppIdDef.APP_ID.D1_CAN_BUS, new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus._462.activity.CarBodyActivityD1"));
         this.put(AppIdDef.APP_ID.INSTRUMENT, new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus._466.activity.GaugesActivity466"));
         this.put(AppIdDef.APP_ID.MOTORAYALE_INFORMATION, new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus._466.activity.DriveActivity466"));
         this.put(AppIdDef.APP_ID.GAS_POWER_MODE, new ComponentName("com.sany.sanyapplication", "com.sany.powermode.MainActivity"));
         this.put(AppIdDef.APP_ID.CAR_TPMS, new ComponentName("com.hzbhd.tpms.car.ui", "com.hzbhd.tpms.car.ui.MainActivity"));
         this.put(AppIdDef.APP_ID.MS, new ComponentName("com.ms.ms2160", "com.ms.ms2160.myapplication.MainActivity"));
         this.put(AppIdDef.APP_ID.TOPPPAL_SERVICE, new ComponentName("com.txznet.aipal", "com.txznet.aipal.view2.MainActivity2"));
         this.put(AppIdDef.APP_ID.TOPPAL_VOICE, new ComponentName("com.txznet.smartadapter", "com.txznet.smartadapter.ui.MainActivity"));
         this.put(AppIdDef.APP_ID.VEHICLE_KTV, new ComponentName("com.lehu.mystyle.boardktv", "com.lehu.mystyle.boardktv.ui.activity.SplashActivity"));
         this.put(AppIdDef.APP_ID.VERSATILE_THEME, new ComponentName("com.dofun.variety", "com.dofun.variety.online.DomesticOnlineActivity"));
         this.put(AppIdDef.APP_ID.SMART_HEAVY_DUTY_TRUCK, new ComponentName("appcan.jerei.zgzq.client", "appcan.jerei.zgzq.client.login.ui.WelcomeActivity"));
         this.put(AppIdDef.APP_ID.OTHER_AMAZON_PRIME_VIDEO, new ComponentName("com.amazon.avod.thirdpartyclient", "com.amazon.avod.thirdpartyclient.LauncherActivity"));
         this.put(AppIdDef.APP_ID.OTHER_APPLE_TV, new ComponentName("com.apple.atve.androidtv.appletv", "com.apple.atve.androidtv.appletv.MainActivity"));
         this.put(AppIdDef.APP_ID.OTHER_DISNEY, new ComponentName("in.startv.hotstar.dplus.tv", "in.startv.hotstar.ui.splash.TVSplashActivity"));
         this.put(AppIdDef.APP_ID.OTHER_HBO_MAX, new ComponentName("com.hbo.hbonow", "com.hbo.hbonow.MainActivity"));
         this.put(AppIdDef.APP_ID.OTHER_HULU, new ComponentName("com.hulu.plus", "com.hulu.features.splash.SplashActivity"));
         this.put(AppIdDef.APP_ID.OTHER_NETFLIX, new ComponentName("com.netflix.mediaclient", "com.netflix.mediaclient.ui.launch.UIWebViewActivity"));
         this.put(AppIdDef.APP_ID.GOOGLE_YOUTUBE_TV, new ComponentName("com.google.android.apps.youtube.unplugged", "com.google.android.apps.youtube.unplugged.startup.activity.SplashActivity"));
         this.put(AppIdDef.APP_ID.OTHER_PANDORA, new ComponentName("com.pandora.android", "com.pandora.android.LauncherActivity"));
         this.put(AppIdDef.APP_ID.OTHER_PARAMOUNTPLUS, new ComponentName("com.cbs.app", "com.paramount.android.pplus.splash.mobile.integration.SplashActivity"));
         this.put(AppIdDef.APP_ID.OTHER_SUNlIGHTEN, new ComponentName("com.lemote.sunlighten", "com.lemote.sunlighten.MainActivity"));
         this.put(AppIdDef.APP_ID.ANDROID_SET_S5, new ComponentName("com.android.launcher3", "com.android.launcher3._s5.view.SetActivity"));
      }
   };
}
